### ISSUE TITLE
problems with installation

### ISSUE THREAD

**Issue by colomet** [washingtonstateuniversity/wsu.edu#122]
@jeremyfelt Why if I have installed in my server WSUWP-spine-parent-theme I can not install wsu.edu? is not a wordpress child theme? Do I need something before the installation?

thanks

**Comment by colomet** [comment]
@jeremyfelt should I use some default plugins or other applications in order to use these child theme?

thanks

**Comment by jeremyfelt** [comment]
Hi @colomet. The WSUWP Spine Parent Theme is the most important part, though there are likely pieces throughout the theme that rely on functions provided by the WSUWP Platform and other various repositories. One key is that the parent theme should be in the `spine` directory for it to be picked up as the correct parent theme.

**Comment by colomet** [comment]
Sorry, `spine`  directory?

**Comment by jeremyfelt** [comment]
Yes, the child theme looks for a parent theme in a directory named `spine`. If you clone the parent repository as `WSUWP-Spine-Parent-Theme`, WordPress is not able to match the two.

**Comment by colomet** [comment]
ok. thanks i will try.
